export interface IColumnInfo {
  table_catalog: string | null;
  table_schema: string;
  table_name: string;
  column_name: string;
  ordinal_position: number;
  column_default: string | null;
  is_nullable: string;
  data_type: string;
  character_maximum_length: number | null;
  character_octet_length: number | null;
  numeric_precision: number | null;
  numeric_precision_radix: number | null;
  numeric_scale: number | null;
  datetime_precision: number | null;
  interval_type: string | null;
  interval_precision: number | null;
  character_set_catalog: string | null;
  character_set_schema: string | null;
  character_set_name: string | null;
  collation_catalog: string | null;
  collation_schema: string | null;
  collation_name: string | null;
  domain_catalog: string | null;
  domain_schema: string | null;
  domain_name: string | null;
  udt_catalog: string | null;
  udt_schema: string | null;
  udt_name: string | null;
  scope_catalog: string | null;
  scope_schema: string | null;
  scope_name: string | null;
  maximum_cardinality: number | null;
  dtd_identifier: string | null;
  is_self_referencing: string;
  is_identity: string;
  identity_generation: string | null;
  identity_start: string | null;
  identity_increment: string | null;
  identity_maximum: string | null;
  identity_minimum: string | null;
  identity_cycle: string | null;
  is_generated: string;
  generation_expression: string | null;
  is_updatable: string;
}
