version: "3.3"
services:
  # sonarqube:
  #   image: sonarqube:latest
  #   container_name: sonarqube
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube-db:5432/sonar
  #     - SONARQUBE_JDBC_USERNAME=sonar
  #     - SONARQUBE_JDBC_PASSWORD=sonar
  #   networks:
  #     - dev_network
  #   depends_on:
  #     - sonarqube-db
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - dev_network
  
  # sonarqube-db:
  #   image: postgres:alpine
  #   container_name: sonarqube-db
  #   environment:
  #     - POSTGRES_USER=sonar
  #     - POSTGRES_PASSWORD=sonar
  #     - POSTGRES_DB=sonar
  #   networks:
  #     - dev_network
  #   volumes:
  #     - sonarqube-db:/var/lib/postgresql/data

networks:
  kafkanet:
    driver: bridge
  main-network:
    driver: bridge
  dev_network:
    driver: bridge

volumes:
  jenkins_home:
  # sonarqube-db:

# ./bin/elasticsearch-reset-password -u elastic -i --url https://localhost:9200
# elasticsearch-create-enrollment-token --scope kibana --url https://localhost:9200/
# docker exec -it a259747181ee sh  kibana-verification-code

# grep vm.max_map_count /etc/sysctl.conf
# sudo sysctl -w vm.max_map_count=262144