version: "3.3"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin@111
      POSTGRES_PASSWORD: admin@111
      POSTGRES_DB: maindb
    ports:
      - "5432:5432"
    networks:
      - main-network

  api:
    container_name: api
    image: 2080600383/low-code-angular16-api
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST_NAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=admin@111
      - DATABASE_PASSWORD=admin@111
      - DATABASE_SCHEMA=maindb
      - DATABASE_TYPE=postgres
      - SERVER_SECRET_KEY=kqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCS9
    ports:
      - 3000:3000
    networks:
      - main-network

  web:
    container_name: web
    image: 2080600383/low-code-angular16-web
    restart: always
    ports: 
      - 4200:4200
    networks:
      - main-network

networks:
  main-network:
    driver: bridge

# ./bin/elasticsearch-reset-password -u elastic -i --url https://localhost:9200
# elasticsearch-create-enrollment-token --scope kibana --url https://localhost:9200/
# docker exec -it a259747181ee sh  kibana-verification-code

# grep vm.max_map_count /etc/sysctl.conf
# sudo sysctl -w vm.max_map_count=262144